image: cappero_laser_odom_diag_2020-05-06-16-26-03.png

# Based on cappero_laser_odom_diag_2020-05-06-16-26-03.world,
# Map width, height, and resolution are 106.9, 49.3, and 0.002, respectively.
# Otherwise, the original occupancy grid map has 2138x987 pixels (width x height).

# Let W is width and H is height, we can get the resolution by taking the ratio :
# Resolution_W = \frac{W_sim}{W_map} = 106.9/2138 \approx 0.05
# Resolution_H = \frac{H_sim}{H_map} = 49.3/987 \approx 0.05

# Original
# resolution: 0.02   # Match the resolution from the .world file
# origin: [-19.6, -5.0, 0.015]  # Origin based on floorplan size/pose

# Modified
resolution: 0.05   # Resolution to align current scan to occupancy grid map
origin: [-49.4, -11.7, 0]

occupied_thresh: 0.65
free_thresh: 0.196
negate: 0

